
/***********************************************************************/
/*                                                                     */
/*  FILE        :Empty.c                                               */
/*  DATE        :Mon, Jan 08, 2007                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.0).     */
/*                                                                     */
/***********************************************************************/
     
#include <stdio.h>
#include <stdlib.h>
#include "qsk_bsp.h"
#include "qsk_lcd.h"
#include "common.h"

#define LCD_SEM 1
#define ENEMY_SEM 2
#define QUEUE_SEM 3

createMessageQueue(1, unsigned long);

// prototypes

void mcu_init(void);	              

/* *******************************************************************
 Description:
 Entry:
 Returns:
 
 Notes:
 
***********************************************************************/ 

void task_A() {
	unsigned long i = 0;
	unsigned long z = 0;
	while(1) {
		p8_0 = !p8_0;
		waitSemaphore(LCD_SEM);
		DisplayString(LCD_LINE1, "T1");
		releaseSemaphore(LCD_SEM);
		
		waitSemaphore(QUEUE_SEM);
		sendMessageQueue(1, z++);
		releaseSemaphore(QUEUE_SEM);
		for( i = 0 ; i < 40000 ; i++ ){
			_asm("NOP");
			_asm("NOP");
			_asm("NOP");
			_asm("NOP");
			_asm("NOP");
		}
	}
}

void task_B() {
	unsigned long i = 0;
	unsigned long z = 0;
	char buf[50] = {0,};
	while(1) {
		p7_4 = !p7_4;
		waitSemaphore(LCD_SEM);
		z = (unsigned long)receiveMessageQueue(1);
		sprintf(buf, "data: %d", z);
		DisplayString(LCD_LINE2, buf);
		releaseSemaphore(LCD_SEM);
		for( i = 0 ; i < 40000 ; i++ ){
			_asm("NOP");
			_asm("NOP");
			_asm("NOP");
			_asm("NOP");
			_asm("NOP");
		}
	}
}

void task_C() {
	while(1) {
		//DisplayString(LCD_LINE1, "T3");
	}	
}

/*
 * CarKing Application
 */
int player_position = 0;
int box1_x = 7;
int box2_x = 3;
int level = 0;
int level_cnt = 0;
int isDead = 0;
int isButtonClick = 0;
extern INT32U tick;

typedef enum {START, DEAD, RUNNING} GAME_STATE;

GAME_STATE gameState = START;

void task_draw() {
	const char box = '#';
	const char player = ')';
	
	while(1) {
		char line1[8] = {' ',' ',' ',' ',' ',' ',' '};
		char line2[8] = {' ',' ',' ',' ',' ',' ',' '};
		
		switch(gameState) {
			case START:
				sprintf(line1, "CARKING");
				sprintf(line2, "RUN: S1");
			break;
			case RUNNING:
				// Draw Boxes
				waitSemaphore(ENEMY_SEM);
				if (box1_x >= 0 && box1_x < 7) line1[box1_x] = box;
				if (box2_x >= 0 && box2_x < 7) line2[box2_x] = box;
				releaseSemaphore(ENEMY_SEM);
		
				// Draw Player
				if (player_position == 0) line1[0] = player;
				else line2[0] = player;
			break;
			case DEAD:
				sprintf(line1, "YOUDEAD");
				sprintf(line2, "HAHAHAH");			
			break;
		}
		
		// Real Draw
		waitSemaphore(LCD_SEM);
		DisplayString(LCD_LINE1, line1);
		DisplayString(LCD_LINE2, line2);
		releaseSemaphore(LCD_SEM);
	}
}

void task_player() {
	while(1) {
		
		if (gameState == RUNNING && isButtonClick == 1) {
			isButtonClick = 0;
			player_position = !player_position;
		}	
	}	
}

void task_logic() {
	while(1) {
		if (gameState == RUNNING) {
			waitSemaphore(ENEMY_SEM);
			if (box1_x == 0 && player_position == 0) gameState = DEAD;
			if (box2_x == 0 && player_position == 1) gameState = DEAD;
			releaseSemaphore(ENEMY_SEM);
		} else if (gameState == DEAD) {
			if (isButtonClick == 1) {
				isButtonClick = 0;
				srand(tick);
				gameState = START;	
			}
		} else {
			if (isButtonClick == 1) {
				isButtonClick = 0;
				// init
				player_position = 0;
				box1_x = 9;
				box2_x = 11;
				level = 0;
				level_cnt = 0;
				
				gameState = RUNNING;	
			}
		}
	}
}

void task_lamp() {
	while(1) {
		switch(gameState) {
			case START:
			break;
			case RUNNING:
			p8_0 = 1;
			p7_2 = 0;
			delay(MSEC_TO_TICKS(1000));
			p7_2 = 1;
			break;
			case DEAD:
			p7_2 = 1;
			p8_0 = 0;
			delay(MSEC_TO_TICKS(1000));
			p8_0 = 1;
			break;	
		}
		delay(MSEC_TO_TICKS(1000));	
	}
}

void task_move() {
	while(1) {
		if (gameState == RUNNING) {
			delay(MSEC_TO_TICKS(5000 - level*500));
		
			waitSemaphore(ENEMY_SEM);
			if (box1_x >= 0) {
				box1_x--;	
			} else {
				srand(tick + 5);
				box1_x = 8 + (rand() % 6);	
			}
		
			if (box2_x >= 0) {
				box2_x--;	
			} else {
				srand(tick + 10);
				box2_x = 8 + (rand() % 6);
				level_cnt++;
				if (level_cnt > 3) {
					level_cnt = 0;
					if (level < 10) level++;	
				}
			}
		
			if (box2_x == box1_x) box1_x += (3 + (rand() % 3)) ;
			else if ((box1_x - box2_x) == 1 || (box2_x - box1_x) == 1) box1_x += (3 + (rand() % 3)) ;
			releaseSemaphore(ENEMY_SEM);
		}
	}
}

void main(void)
{	
//	ku_tcb t1, t2;
	INT16U *stk;
	
	mcu_init();
	
	// Initializing
	InitDisplay();
	initSemaphore();
	
	// Crete Semaphore
	createSemaphore(LCD_SEM);
	createSemaphore(ENEMY_SEM);
	createSemaphore(QUEUE_SEM);
	
	// SET LEDs Direction
	pd8_0 = 1;
	pd7_4 = 1;
	pd7_2 = 1;
	
	// SET LEDs Default Color
	p8_0 = 1; // RED
	p7_4 = 1; // YELLOW
	p7_2 = 1; // GREEN
	//
	
	// Button Init
	// S101
	pd8_1 = 0;
	ilvl0_int1ic = 1;
	ilvl1_int1ic = 1;
	ilvl2_int1ic = 1;
	pol_int1ic = 0;
	
	SAVE_ISP(stk);
	InitSched();
	InitTask(task_draw, stk-100, 0);
	InitTask(task_logic, stk-200, 1);
	InitTask(task_move, stk-300, 2);
	InitTask(task_player, stk-400, 3);
	InitTask(task_lamp, stk-500, 4);
	
	//InitTask(task_A, stk-100, 0);
	//InitTask(task_B, stk-200, 1);
	//InitTask(task_C, stk-300, 2);
	
	StartSched();
}
